apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS nodedb;
		USE nodedb;
		CREATE TABLE peoples(id int not null auto_increment, name varchar(255), primary key(id));
