cat apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-node
  template:
    metadata:
      labels:
        app: app-node
    spec:
      containers:
      - name: app-node
        image: lgcosta/app-node-15:1.0
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app  # Seleciona os pods que têm o label 'app: nodejs-app'
  ports:
    - protocol: TCP
      port: 3000  # Porta que o serviço expõe no cluster
      targetPort: 3000  # Porta em que o contêiner está escutando
  type: ClusterIP  # Tipo de serviço (pode ser NodePort, LoadBalancer, etc.)

  
